pouchdb-community/ember-pouch

lib/pouchdb-adapter.js

`DS.Store` can attempt to combine multiple `find` calls from the same run loop into a single `findMany` call. This is enabled by default on `DS.Adapter`, but disabled by default on `DS.RESTAdapter` under the assumption that most REST APIs don't allow this type of request.
Since ember-pouch provides `#findMany`, it makes sense to enable this feature.
Refs:
* [DS.Adapter#coalesceFindRequests](http://emberjs.com/api/data/classes/DS.Adapter.html#property_coalesceFindRequests)
* [DS.RESTAdapter#coalesceFindRequests](http://emberjs.com/api/data/classes/DS.RESTAdapter.html#property_coalesceFindRequests)

Enable coalesceFindRequests by default

---

README.md
lib/pouchdb-adapter.js

Allows ember-pouch to support the documentType schema feature implemented in nolanlawson/relational-pouch#21. See the changes in the README for more details.

Pass documentType through to relational-pouch if provided

---

lib/pouchdb-adapter.js

Style, error-avoidance, and performance fixes for the automatic changes watcher. There are details in the commits; at a high-level:
* Don't throw exceptions when there's a change to a design doc or other non-relational_pouch doc.
* Don't keep changes around in memory since the watcher doesn't need them.
* Don't load records into the store that aren't already there. This makes a huge speed and memory difference on large databases.
All of these changes were initially suggested & implemented by my colleague @moses.

Changes watcher improvements

---

.travis.yml
addon/adapters/pouch.js
tests/dummy/app/adapters/application.js
tests/dummy/app/models/taco-soup.js
tests/integration/adapters/pouch-test.js

This is my suggestion for #62, based on my desire to prevent all existing ember-pouch users from having to do a data migration as discussed in #63.
It also includes a set of very basic integration tests. If this feature doesn't get integrated, they should still be usable on their own. (I wrote them to verify that this change did preserve the prior behavior.)

Use modelName instead of typeKey when available, but preserve existing ID generation behavior

---

.travis.yml
bower.json
config/ember-try.js
tests/integration/adapters/pouch-test.js

There is code in place to support versions back to beta.15, so it seems like we should have the tests run that far back. We can always drop support in the future.
Each ember-data version is paired with the latest bugfix of the ember version that was current when that ember-data version was released.
This PR also makes it so that a failure in one of the symbolic versions (release, beta, canary) does not make the whole build a failure. Rationale: If there’s an incompatibility between a future version of ember or ember-data and ember-pouch, that should be fixed. But it shouldn’t block accepting changes that do pass on all the supported versions. (If there were a way to have travis run a separate build whenever there was a new release/beta/canary version, that would be great. But I don't …

Ember-try config for all supported versions of ember-data, plus fixes for the tests on ember-data beta19 and later

---

addon/adapters/pouch.js

See #79 and #80 for discussions of why, and why this covers the individual record case only.

Ember-data never needs to reload ember-pouch records

---

addon/adapters/pouch.js

Right now in the ember adapter, the code is using this.db to reference the PouchDB used.  For most use cases this works fine, but it doesn't work if you are trying to set the db via injection doing something like this:
```javascript
var configDB = new PouchDB('config');
application.register('pouchdb:configdb', configDB, {instantiate: false});
application.inject('adapter', 'db', 'pouchdb:configdb');  
```
In the example above this.db will be undefined, but this.get('db') will return the defined PouchDB.
This pull request simply changes the this.db references to this.get('db') so that the PouchDB can be injected or can be used the way it is defined in the readme.

Change access to db property to use Ember.get

---

addon/adapters/pouch.js
bower.json
tests/integration/adapters/pouch-test.js

fixes #78
This change will be incompatible with the betas of Ember Data, just fyi. Users will have to upgrade Ember Data as well.

remove deprecation warnings for 1.13

---

README.md
blueprints/.jshintrc
blueprints/pouch-model/files/__root__/__path__/__name__.js
blueprints/pouch-model/index.js

This replaces https://github.com/nolanlawson/ember-pouch/pull/90
It creates a blueprint to easily create model files that import from `ember-pouch/model`
usage: `ember g pouch-model <model-name>`

Added blueprint for pouch-model

---

README.md
addon/adapters/pouch.js
tests/dummy/app/adapters/taco-salad.js
tests/dummy/app/models/taco-salad.js
tests/integration/adapters/pouch-default-change-watcher-test.js

Pouch adapter now calls a hook method when encountering a change for a record that is not yet loaded.
- The hook is no-op by default, to match present behavior and performance profile
- Added a test demonstrating use of the hook to load the new data into the ember-data store
@lukemelia / @chrislopresto

Make adapter call a hook when encountering a change for a record that is not yet loaded.

---

blueprints/pouch-model/index.js

As [suggested by @fsmanuel](https://github.com/nolanlawson/ember-pouch/issues/128#issuecomment-227289620), this fixes [@fredguth’s error generating a model](https://github.com/nolanlawson/ember-pouch/issues/128#issuecomment-227278998).
I’m not sure how this fix should affect the version number. Or maybe some kind of dual import should happen, to keep backward compatibility. Thoughts?
For now, @fredguth, you could just edit `node_modules/ember-pouch/blueprints/pouch-model/index.js` with this change and you’d be able to generate the model.

Correct import of Ember Data model blueprint

---

.travis.yml
README.md
addon/serializers/pouch.js
addon/transforms/attachment.js
addon/transforms/attachments.js
app/transforms/attachment.js
app/transforms/attachments.js
bower.json
config/ember-try.js
ember-cli-build.js
index.js
tests/dummy/app/adapters/taco-salad.js
tests/dummy/app/models/taco-recipe.js
tests/dummy/app/serializers/taco-recipe.js
tests/integration/serializers/pouch-test.js
tests/unit/transforms/attachment-test.js
tests/unit/transforms/attachments-test.js

This PR contains @stevebest's changes in #135, as well as the changes that I've made.
- Add `attachment` and `attachments` transforms
- Serializer changes to support these
- Integration test that covers the new functionality.
My adapter changes are not compatible with ember-data 1.13. Unless there's a strong need to keep supporting this I suggest we drop support for this and support ember-data >= 2.x. @nolanlawson what are your thoughts on this?

Attachments transform

---

.travis.yml
README.md
addon/adapters/pouch.js
addon/serializers/pouch.js
addon/transforms/attachment.js
addon/transforms/attachments.js
app/transforms/attachment.js
app/transforms/attachments.js
blueprints/ember-pouch/index.js
blueprints/pouch-model/index.js
bower.json
config/ember-try.js
ember-cli-build.js
index.js
package.json
tests/dummy/app/adapters/taco-salad.js
tests/dummy/app/models/smasher.js
tests/dummy/app/models/taco-recipe.js
tests/dummy/app/serializers/taco-recipe.js
tests/integration/adapters/pouch-basics-test.js
tests/integration/serializers/pouch-test.js
tests/unit/transforms/attachments-test.js

Usage:
MyModel.query({selector: { name: "Mario" }, sort: ["name"]})
MyModel.query({selector: {debut: {$gte: 1990}})
MyModel.query({selector: { series: "Mario" }, sort: [{series: "desc"}, {debut: "desc"}]})
MyModel.queryRecord({selector: { name: "Mario" }})

implement glue code for query and queryRecord using pouchdb-find

---

README.md

This should be released on npm with a major version bump because we're adding new functionality and removing support for ember-data < 2.0. I've referred to v4.0.0 in the changelog.

Updated README and changelog

---

README.md

Created documentation for query, queryRecord and createIndex.

Created documentation for query and queryRecord

---

README.md

`DS.attr('attachment')` should be `DS.attr('attachments')`

Fix attachments typo in README

---

addon/adapters/pouch.js
addon/serializers/pouch.js
package.json

this is less radical than #173

update ember-getowner-polyfill to remove deprecation warnings

---

README.md

Fixes the example code and also adds some helpful instructions that are not initially obvious.
The comment regarding index matching is pulled from https://github.com/nolanlawson/pouchdb-find/blob/master/lib/adapters/local/find/query-planner.js#L121

Fix sort documentation and add additional notes

---

README.md

CSP plugin was removed as a default in Ember CLI v2.3.0

Correct Security documentation

---

.travis.yml
bower.json
config/ember-try.js
package.json
tests/integration/adapters/pouch-basics-test.js

This wont work for canary tests, but npm is the future and bower is going away. Also changed minimum ember version tested to 2.4

use npm for ember-source

---

.travis.yml
config/ember-try.js

We can still use the 'normal' components way, don't know why I thought this didn't work earlier. Could have sworn that it gave some errors...
But is working again now.

re-enable canary testing

---

.eslintrc.js
.gitignore
.npmignore
.travis.yml
addon/adapters/pouch.js
addon/serializers/pouch.js
config/ember-try.js
config/environment.js
ember-cli-build.js
index.js
package.json
testem.js
tests/.eslintrc.js
tests/dummy/app/app.js
tests/dummy/app/templates/application.hbs
tests/dummy/config/environment.js
tests/dummy/config/targets.js
tests/helpers/module-for-acceptance.js
tests/helpers/module-for-pouch-acceptance.js
tests/helpers/start-app.js
tests/index.html
tests/integration/adapters/pouch-basics-test.js
tests/integration/serializers/pouch-test.js
tests/test-helper.js

Upgrade project to ember-cli 2.14.1 and use pouchdb 6.3.4.  Also updated tests to pass under eslint and use LTS versions of Ember CLI on travis.

Update Ember CLI and PouchDB

---

index.js
package.json

Pouchdb-find is bundled in relational-pouch now.
Should be a non breaking change for this package.
Travis can only be run after relational-pouch 2.0.0 is published.

Bundle find

---

addon/adapters/pouch.js

I had issues where in acceptance tests an adapter from the previous run would fire on changes to the database of an adapter from the current run...

clean up db changes listener

---

addon/adapters/pouch.js

right now when using `query`, the ember-pouch adapter actually returns all document types from the pouchdb that match the selector...

filter results of pouch adapter query by correct type

---

.travis.yml
bower.json
config/ember-try.js
ember-cli-build.js
package.json
testem.js
tests/dummy/app/app.js
tests/dummy/app/index.html
tests/dummy/app/router.js
tests/dummy/config/environment.js
tests/helpers/destroy-app.js
tests/helpers/module-for-acceptance.js
tests/helpers/start-app.js

This is a pretty hackish solution to [this problem](https://github.com/ember-cli/ember-try/issues/125), also discussed [here](https://github.com/ember-cli/ember-try/issues/133): `ember-try` uses the presence of a `yarn` command to determine whether to `yarn install`. Something was [going wrong with the `yarn install`](https://travis-ci.org/pouchdb-community/ember-pouch/jobs/257985277#L3444-L3454) on the `ember-release` and `ember-beta` scenarios.
This fixes those scenarios but then breaks the ones before them, the inverse of what was happening!
I’m going to ask over on the `ember-try` thread about whether it’s possible to bypass Yarn more elegantly. I’ll also see if I can override Ember CLI’s built-in `ember-try` version with an older one that doesn’t use Yarn.

Fix some jobs on Travis Trusty

---

.travis.yml
config/ember-try.js

Thanks to @jlami for [pointing out](https://github.com/pouchdb-community/ember-pouch/pull/187#issuecomment-343308963) that I mistakenly deleted this.
I haven’t run the tests locally, I wouldn’t be surprised if this still needs some tweaking. We’ll see!

Restore ember-try configuration for Ember Data

---

addon/adapters/pouch.js

Possible solution for #188
Will look for a better solution

Ignore same revision changes

---

README.md

#207 Update documentation about Offline First

---

README.md
addon/adapters/pouch.js
addon/serializers/pouch.js
addon/utils.js
tests/dummy/app/adapter.js
tests/dummy/app/adapters/application.js
tests/dummy/app/adapters/taco-salad.js
tests/dummy/config/environment.js
tests/integration/adapters/pouch-basics-test.js

emberpouch -> emberPouch
dontsave -> save
dontsavehasmany -> saveHasMany

config changes

---

.travis.yml
config/ember-try.js
tests/integration/adapters/pouch-basics-test.js

Cherry-picked from #246 
Broadens test support matrix (Closes #242) and fixes test suite race condition with `store.unloadAll` that starts appearing in these newer versions (Closes #243).

Update test matrix to include 2.18, 3.4, 3.8, and 3.12

---

config/ember-try.js

Needed since ember-data went mono-repo which requires build steps

Fix ember-try ember-data canary

---

blueprints/pouch-adapter/files/__root__/adapters/__name__.js

Seems when ember-pouch was updated for Ember Octane the old blue print was not correctly removed. This PR should fix this.

Fix Adapter Blueprint for Ember Octane

---

README.md

I recently added this package to a new project and had some trouble getting the app to load and found the following error in the console: `Error: Please set the `db` property on the adapter.`. After changing the setup to use class properties instead it worked!

Update README application adapter example to use JS classes
